version: '3.8'
services:
  db:
    image: postgres:15
    container_name: strava_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strava
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .:/workspace
volumes:
  pgdata:
